%see doc on designfilt
lpFilt = designfilt('lowpassfir', 'PassbandFrequency', 0.25,...
             'StopbandFrequency', 0.35, 'PassbandRipple', 0.5, ...
             'StopbandAttenuation', 65, 'DesignMethod', 'kaiserwin');
         
